### ISSUE TITLE
testCases.xsd schema validation

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#58] opened 2017-09-18 15:54 UTC
I've tried to validate the schema of dmn and xml files from TestCases folder.

The dmn files are fine. Some of the xml tests are failing validation due to missing nillable attribute in the testCases.xsd schema.

Adding nillable = "true" to complexType valueType solved the issue:

		<xs:choice>
			<xs:element name="value" type="xs:anySimpleType" nillable="true"/>
			<xs:element name="component" maxOccurs="unbounded">

I'll raise a pull request if we are happy with this change.

**Comment by opatrascoiu** [comment] 2017-09-18 16:58
We also need to change the marshaller module.

**Comment by opatrascoiu** [comment] 2017-09-18 17:01
I suggest using jaxb to generate the pojos from xsd in the marshaller module.

**Comment by agilepro** [comment] 2017-09-29 17:15
These like it is very reasonable.  We solved the null problem recently, and conceivable that we forgot to go back and change the schema.  Please submit the modified schema as a change request.  Seems good to me, but I would like confirmations from those who actually run the tests.

**Comment by arthware** [comment] 2017-10-13 15:25
I am still struggling with null as expected value. Trying to set null as expectedValue on ValueType 

`ValueType expectedValue = factory.createValueType();
 expectedValue.setValue(null);`

throws an error. Looking at the ValueType class in marshaller, I don't see any indication that "value" is required=false ...
```
public class ValueType {

    @XmlSchemaType(name = "anySimpleType")
    protected Object value;
```
https://github.com/dmn-tck/tck/blob/master/runners/dmn-tck-marshaller/src/main/java/org/omg/dmn/tck/marshaller/_20160719/ValueType.java

Any hints?

**Comment by etirelli** [comment] 2017-10-13 16:00
@arthware I don't think the marshaller was re-generated after the changes to the schema. The original marshaller was created by Tim. 

We should probably change the schema to include the error flag we were discussing and then regenerate the classes to solve both requests.

**Comment by arthware** [comment] 2017-10-16 13:30
@etirelli The problem is/was that the testCase.xsd file is available twice in the project: 
`dmn-tck-marshaller/src/main/resources/schema/testCase.xsd` and
`TestCases/testCase.xsd`. The files diverged and that caused confusion. 

Anywa: We are currently fixing that problem and also update the marshaller module, to always reflect schema changes. 
I will provide a PR once we are ready.

**Comment by opatrascoiu** [comment] 2017-10-16 14:28
We should have one single xsd file and use jaxb to generate. For example,

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>jaxb2-maven-plugin</artifactId>
                <version>2.2</version>
                <executions>
                    <execution>
                        <id>tck</id>
                        <configuration>
                            <sources>
                                <source>${tck.schema}</source>
                            </sources>
                            <outputDirectory>${jaxb.generated.tck}</outputDirectory>
                            <clearOutputDir>false</clearOutputDir>
                            <noPackageLevelAnnotations>false</noPackageLevelAnnotations>
                            <packageName>org.omg.dmn.tck.marshaller._20160719</packageName>
                        </configuration>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${jaxb.generated.tck}</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

Where ${jaxb.generated.tck} is ${project.basedir}/target/generated-sources/jaxb

I don't mind making the change if we agree on this approach.

**Comment by arthware** [comment] 2017-10-16 14:37
@opatrascoiu  Agreed. Thats what we have done too, basically. I could provide a PR tomorrow.

**Comment by opatrascoiu** [comment] 2017-10-16 14:40
I looks like we have 4 testCases.xsd files. We should have only one, maybe in the same place with the dmn.xsd file.

**Comment by arthware** [comment] 2017-10-16 15:03
Yep, thats the one we took: In `TestCases/testCases.xsd`. I'll see if I can find the other ones too ;-)

**Comment by etirelli** [comment] 2017-10-16 17:58
agreed, there should be a single XSD file in a well known location or we will always face issues. Thank you for looking into it @arthware . Feel free to remove all duplicates in your PR.

**Comment by etirelli** [comment] 2017-10-21 13:57
PR merged. Closing the ticket.

Thank you @arthware !

**Closed by etirelli** 2017-10-21 13:57 UTC
